sudo: true
language: python
python:
- 3.7
cache: pip
before_install:
- export BOTO_CONFIG=/dev/null
install:
- pip install travispy
- pip install -e ".[aws,test]"
script:
- python -m pytest --cov=drift/ --disable-warnings
- echo $(git describe --abbrev=0 --tags) > drift/VERSION
after_success:
- codecov
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch:
    - develop
    - "/(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$/"
  user: __token__
  password:
    secure: PUVylYaztJJbWqgSwSNvz0/FOZ7iNln37sSVBi5a/xIQEsk/doOoEWgdtS69JvSdbrea+EWCzs3boe18cEM/5cXAkaI7PM0B0U7VgmkwQSgpqH5A/JVy2kYJM1suzuSo4UxQ4zATvcCV1fd6MqlEu8Tn00vfDjW71jcpZfiAnpH9UKFn5o7j5DmjseuPbjqaeVWDN5e7o6umfFKoiCpDvS1H/lfkuOCQ5BknOsh2R16Whj12jM/bzxp6S0RWUvQeUEGdHAvmNkXZm1NL3E9pB1fWybr3W5mHJYF/QcDY2J93xEL8Vl72GjsQtHgtuxQmLRbFP79F9duwr0vyORAexQ/NUWSWLVlj0qUOeJpAeCJqjZJtArEkniyZ/8qn+hjH9k8hHyXgxh8dckEswCDhDxwMR1GqgbAjRszF/x2KPAqcnL5pdfGALi2Fxzrqp8ZW+LP/0sqPv0KN5h6l3xj0sasZfYNrJfsDRPZe+/IgBF/yLNhmmqvc0Vaazg/v8A4VG6kPUJXRhWbNkzwBfyrJjKHhGAXYAXD2i8ZA9bb3n+Ulmol+TDoO5RS8tvZ7UvmBkmvoI/ujajsAlREQVDNhWAhLK/cnBzPcbqQgAdfOfSn/64TlZraHMgxN9H2Z/7zEIX6qgtmFhiWKa6hqQclBGvOT2nAn2ULspIBEsZSVxlA=
notifications:
  email:
    secure: gyhoRaM8tCtRJ/1eG7O6wPCNtZuFDBob+XK/W0CianwtqATtZlkxADSyy0O7+2pczV28BnRPGKs2Bz43PwrXDA1YIVXfa8B+F19pXJt+g1c6a7l2TrH4yDnkZADxC8j0qvUptEHNTzq9DX/w+73WgrUJvki4YDdcPk0YXCTMtIh5e/xw05A1nCmNGXZzWMPPjSHaqpUa39YhCdDGWh/mpeOXCKgWEsyRF3lN+wNrwXGJUJTBs0hpV07aCY0X1CYFETO4bhsRIpT67qwtpL/Y4ZjUbaP26iZcNdRFa2HVJu1r8qhGU6W/7gNPBwwhDhUZD41RDeFtxMsav/fpu4f0zQtwYB4giZNOCF4d+m+5p0dz2XVVw1ZDHy+5ZKeKWck8ZQEEipk89PvEB9LhcvSjN8DwOK31z5YHu1PXawb40RUC7AOcVwsxhUxQrUCLcjDG4f8ae7PZj2KYFchIrf+9cA55JLD/pG40z4ns18VXIpTymfZUs8NmR36+IAtXtxyrlxlRKxtH/76fd14Hpzi8hApO/fSjMOty0935iiHfj5BWXbRcZGe3QhnWR5TKRjilmSZcuvpo0eBckIHg9IIToFh+IAir/yKGE0bUNFfuasGk0Ks9p6Hgfv4olBtbtwz4CP6d0UQD1VE2XXeRmIy47QFCA1894QOfaUavZr+SOJw=
  slack:
    on_pull_requests: false
    rooms:
    - secure: p3mM+C7A/E6Ze2Tn3h2oRxeTmkMEPLQiXwYa/6DpsWO6vlGnAQVKZtu28z9LQ/xvMRdNINS9X2JYtdCbdvG18quGd4cfAYCkKRWjGwPdcWYKMMVNLeibjJGMpcTsYV645A4DER2J2vCFoMHujqGnjSPLOwXI7XryFJ8j6/feAJc4blh/jRw1kGNLff5rc7ACVf+uqQIklhYXQUFaR3SwpxWNoQC3anByjFgdOvEw97zL10xgqlZV4UDpnWZj6G7hlYh0zV4TpLjMiiB1MGo1j5UZhcam23Ck8BNgBnSZ7wx7z00DNInermQvyoxvRfQMKmc3e31J8O4aqXoz6Wo4ZPF9XD+FU9y5KB1YOQcIzA2e+5UIQlPRO2ZpMYxOt+LNJY/1KJ5998bV9NIv8usCCn0JS/VQ09OigBNBcPvhTgrjhDsOZtLqo4FoYH0X3ZPnMBtkyS1cHF7lxPG/1S+Ma/ATHPoiJXr6mhCpPQsayAaTRJSwRhcgXnJoKaJ79nw3hdVXFnAs5jeIqSReeSKY+mihmDHirSj3oEWzuq87X3WpLOc0g1Bp038MK20yEkuvECLf0GaDTNXqIXS7xScz9XNoS2c851Jdp99W7okWTeZNEkYolTqcTySlA7PcBtoqfqn04E7v5Vr4GfTFKAhx3t2ccqLdGzaOvhYndbzXsao=
    - secure: YLfOiOzz2Q7Po/WS5CHvOG0AUYks2Cpd/al9/LSK+EVK9JNjr6EovI8hvGGvGd1RIBGnNhDMcWyiacYenlk3GLoGTeOahTmSROs2A3xjOxz3ltx3ryxiLIHEzYcTEoNHc0XbTyklyQ8lO7TVyZdl8b8h0CKQhfviF8LcMmcU9NrhvE7SvUf6Nte5F9EXu4/moqvXYWBpF2+9JWQx7WebmzoRg3dB7zoZYjQtDkTNF1xFakFnpPY2cyxEi1OW7LgdDlXzuTPPZYutkdbYMCG79x+LC4nZNKnaaOivx61Jrq4+d4Gjgw8yVDQuwhuhhC93DOpm4FLzDsLHP6Mm1hdrUXSwKLsQ6mqXWVFAS+VV2Nz9UX6IeVWNtb0YN2Ddn+RvWQudNpmshEWTPrkJZJ0nsdZGX72wLStSHlSB04/SlyXxrNN6ppIJ7Pa2cUd/aVguY3A1xym8HlMNT6buYgvGb0UwxAcFqFywlL91gOolXlr8Z7ZSxmQ9MAoVmjbxp/cYUhh+1TES41pJNWkEw4nU6T/XFilw02jYf7lJG9bU1dintZ2KI1IsXYVTZCe8KxERh0pc1iXqlZm3e1ZgEPPZKtTcq2bq9+r5T7IP56o+VO5rqPLRFUTECwC3ZM++uMwYtI7QGdVB85aSre9omf/47Q+rCGovopUNbWUY7UEja30=
env:
  global:
    secure: PJNBfkbp3NHGpyl2vGFDkabw+e9XkQ02SnQHnrwFRTXLG+qcOwac6HzbustsZ2UYD3yMytvHeryRdhLqO6xvRluOwM80yN69klyLOdPB37KVVI9B82oJ3s2f7lfWjDEKZVv2SyvnGISgGQ+18Cqk/PFdKPIHL6al4IiZf3aQacPvrLbZ0iYjZhFtzpg6xbj7vd01DCCf2jwyZMMn6In5oUZMZsHNAk/DgIhpXCz3VPrF0B69VW3hNjF8Ichyww2UVTi18twA2V4yaH3CTaLH/d+84fJ+x0awWJ4TDWOf5WqyhOPG/I96fXRJg1uuAf4FHUS4fp8pgXEswygMNlgadDXnqBDw/5lrUmIwQe7Iq/Fq535tNP4omjJ10qBggzAAV1y3WsMU474sM96yWEbsPKvak23LbXKZ2SfcI6SyjMXDpBrp6Bq9FXJFwGi3jgk3fo0io4aHeGz2n6nGlvJ+29iSs3OUEs7Y6bPO8HlYbwc44fd17RV/xWy94Ud9SJBcM2KZX5jQDUYc0MuupiTvo0UQp+WC+unQYTj7WpaNcZjNjK22RJKbiYSUBZ/Sk6o7s0GX+HJ8s0fWwmTbZIi7YGhju2ndVTi8JKAR6NFpLs9H98UdsCgq3jGYQxD8gJaLHBA+ugnDjRHxxwF02eJ2Tp6Dr/MIcCeLfruptDzrkEw=
