name: publish-to-pypi
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[aws,test]"
      - name: Run PyTest
        run: pytest .

  publish:
    runs-on: ubuntu-latest
    steps:
