name: Build and Publish
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        env:
          PYPI_USERNAME: ${{ secrets.DG_TWINE_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.DG_TWINE_PASSWORD }}
          PYPI_INDEX_URL: ${{ secrets.DG_NEXUS_PYPI_URL }}
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e ".[aws,test]"

      - name: Run PyTest
        run: pytest .

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.x'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
        with:
          useConfigFile: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        env:
          PYPI_USERNAME: ${{ secrets.DG_TWINE_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.DG_TWINE_PASSWORD }}
          PYPI_REPOSITORY_URL: ${{ secrets.DG_NEXUS_PYPI_URL }}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install -e ".[aws,test]"

      - name: Stamp version
        run: |
          echo ${{ steps.gitversion.outputs.semVer }} > drift/VERSION

      - name: Publish to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.DG_TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.DG_TWINE_PASSWORD }}
          TWINE_REPOSITORY_URL: ${{ secrets.DG_NEXUS_PYPI_URL }}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/*
